### ISSUE TITLE
Actividad 4 Diseño de objeto 3d en Blender

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-promastergamer#1]

**Comment by FedericoVictorianoSierra** [comment]
[Actividad 4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-promastergamer/files/14653305/Actividad.4.pdf)

**Comment by josealfredo79** [comment]
Cual es la calificacion..???

**Comment by NoeliaGlez** [comment]
calificación 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado...
